//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbObjectsInfo
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Table", Namespace="http://tempuri.org/")]
    public partial class Table : object
    {
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DbObjectsInfo.IDbObjectsInfoService")]
    public interface IDbObjectsInfoService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDbObjectsInfoService/GetTables", ReplyAction="*")]
        DbObjectsInfo.Table[] GetTables();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDbObjectsInfoService/GetTables", ReplyAction="*")]
        System.Threading.Tasks.Task<DbObjectsInfo.Table[]> GetTablesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface IDbObjectsInfoServiceChannel : DbObjectsInfo.IDbObjectsInfoService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class DbObjectsInfoServiceClient : System.ServiceModel.ClientBase<DbObjectsInfo.IDbObjectsInfoService>, DbObjectsInfo.IDbObjectsInfoService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public DbObjectsInfoServiceClient() : 
                base(DbObjectsInfoServiceClient.GetDefaultBinding(), DbObjectsInfoServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IDbObjectsInfoService_soap.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DbObjectsInfoServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(DbObjectsInfoServiceClient.GetBindingForEndpoint(endpointConfiguration), DbObjectsInfoServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DbObjectsInfoServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(DbObjectsInfoServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DbObjectsInfoServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(DbObjectsInfoServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DbObjectsInfoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public DbObjectsInfo.Table[] GetTables()
        {
            return base.Channel.GetTables();
        }
        
        public System.Threading.Tasks.Task<DbObjectsInfo.Table[]> GetTablesAsync()
        {
            return base.Channel.GetTablesAsync();
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IDbObjectsInfoService_soap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IDbObjectsInfoService_soap))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:5000/DbObjectsInfoService.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return DbObjectsInfoServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IDbObjectsInfoService_soap);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return DbObjectsInfoServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IDbObjectsInfoService_soap);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IDbObjectsInfoService_soap,
        }
    }
}
